server:
    port: ${PORT}
    
spring:
  main:
    web-application-type: reactive
  profiles:
    default: ${PROFILE}
  application:
    name: Maple Cloud Gateway
---
spring:
  config:
    activate:
      on-profile: ${PROFILE}

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
      routes:
        - id: auth-server
          uri: https://auth-api.root101.dev
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<segment>.*), /latest/$\{segment}
        - id: expenses-management
          uri: https://expenses-management-api.root101.dev
          predicates:
            - Path=/expenses-management/**
          filters:
            - RewritePath=/expenses-management/(?<segment>.*), /latest/$\{segment}