server:
  port: ${PORT:8080}

spring:
  main:
    web-application-type: reactive
  profiles:
    default: ${PROFILE:default}
  application:
    name: ${APPLICATION_NAME:Api-Gateway}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  r2dbc:
    #Variables must be available at compile time (since we started using the native image in v4.1.0), so they are set by default and then overridden with the real values
    url: r2dbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:api-gateway}          #r2dbc:postgresql:/host:port/db-name
    username: ${DB_USERNAME:postgres}                                                            #postgres
    password: ${DB_PASSWORD:admin123}                                                            #admin123
    pool:
      enabled: true

  flyway:
    enabled: true                                                                                #To enable disable the use of railway
    baselineOnMigrate: true
    #Variables must be available at compile time (since we started using the native image in v4.1.0), so they are set by default and then overridden with the real values
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:api-gateway}
    user: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:admin123}
    locations: classpath:db/migration

app:
  defaults:
    username: admin
    password: admin123**
  admin:
    username: ${ADMIN_USERNAME:${app.defaults.username}}
    password: ${ADMIN_PASSWORD:${app.defaults.password}}
    role: ROLE_GATEWAY_ADMIN
    base-path: ${ADMIN_PATH:_admin}
  logs:
    maintainForDays: ${MAINTAIN_LOGS_FOR_DAYS:14}
