server:
  port: ${PORT:8080}

spring:
  main:
    web-application-type: reactive
  profiles:
    default: ${PROFILE:default}
  application:
    name: ${APPLICATION_NAME:Api-Gateway}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}          #jdbc:postgresql:/host:port/db-name?stringtype=unspecified
    username: ${DB_USERNAME}                                          #postgres
    password: ${DB_PASSWORD}                                          #admin123
    pool:
      enabled: true
app:
  defaults:
    username: admin
    password: admin123**
  admin:
    username: ${ADMIN_USERNAME:${app.defaults.username}}
    password: ${ADMIN_PASSWORD:${app.defaults.password}}
    role: ROLE_GATEWAY_ADMIN
    base-path: ${ADMIN_PATH:_admin}
