server:
  port: ${PORT:8080}

spring:
  main:
    web-application-type: reactive
  profiles:
    default: ${PROFILE:default}
  application:
    name: ${APPLICATION_NAME:Api-Gateway}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}                  #jdbc:postgresql:/host:port/db-name?stringtype=unspecified
    username: ${DB_USERNAME}        #postgres
    password: ${DB_PASSWORD}        #admin123
app:
  defaults:
    username: admin
    password: admin123**
  admin:
    username: ${ADMIN_USERNAME:${app.defaults.username}}
    password: ${ADMIN_PASSWORD:${app.defaults.password}}
    role: ROLE_GATEWAY_ADMIN
    base-path: ${ADMIN_PATH:_admin}
